### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by millsoft** [wshafer/psr11-flysystem#4]
Hi, how am I supposed to use flysystem plugins? I tried to do something like this:

```php
        $this->fileSystem = $this->container['fileSystem'];
        $this->fileSystem->addPlugin(new \League\Flysystem\Plugin\ListPaths());
```

(like in the flysystem doc) I get:
`Call to undefined method WShafer\PSR11FlySystem\FlySystemFactory::addPlugin()`

edit:

I added the plugin like in your documentation:

```php
        'fileSystems' => [
            'default' => [
                'adaptor' => 'default',
                'plugins' => [
                    new \League\Flysystem\Plugin\ListPaths()
                ]
            ],
        ],
```

but now when I call that plugin `$this->fileSystem->listPaths("/")` I get:
`Call to undefined method WShafer\PSR11FlySystem\FlySystemFactory::listPaths()`
... because it is not a PSR11FlySystem Plugin, it should use the League\Flysystem Namespace... and advice how to accomplish this?

**Comment by wshafer** [comment]
The factory pulls the plugin from the container by name.  So an example using Zend ServiceManager would be like this...

```
...
        'fileSystems' => [
            'default' => [
                'adaptor' => 'default',
                'plugins' => [
                    \League\Flysystem\Plugin\ListPaths::class
                        => \League\Flysystem\Plugin\ListPaths::class
                ]
            ],
        ],
...
```

Then in your `dependencies`  you'd add the service to the 'invokables' like this:

```
return [
    'dependencies' => [
        // Use 'invokables' for constructor-less services, or services that do
        // not require arguments to the constructor. Map a service name to the
        // class name.
        'invokables' => [
            \League\Flysystem\Plugin\ListPaths::class
                => \League\Flysystem\Plugin\ListPaths::class
        ],
    ],
];
```

Hope that helps
